/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.clan;

import controller.ClientController;
import domain.Clan;
import domain.Kategorija;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.TableModelIzborClana;

public class FormIzborClana extends javax.swing.JDialog {

    private Kategorija kategorija;
    private Clan izabraniClan;

    public FormIzborClana(java.awt.Window parent, boolean modal, Kategorija kategorija) {
        super(parent, modal ? ModalityType.APPLICATION_MODAL : ModalityType.MODELESS);
        initComponents();
        this.kategorija = kategorija;
        setTitle("Izbor clana - kategorija: " + kategorija);
        lblKategorija.setText(String.valueOf(kategorija));
        tblClanovi.setModel(new TableModelIzborClana());
        getRootPane().setDefaultButton(btnIzaberi);
        setLocationRelativeTo(parent);
        ucitajClanove("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblKategorija = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClanovi = new javax.swing.JTable();
        btnIzaberi = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izbor clana");

        jLabel2.setText("Kategorija:");

        lblKategorija.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblKategorija.setText("-");

        jLabel1.setText("Pretraga (ime, prezime ili email):");

        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClanovi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblClanovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClanoviMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClanovi);

        btnIzaberi.setBackground(new java.awt.Color(153, 204, 255));
        btnIzaberi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzaberi.setText("Izaberi clana");
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKategorija)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPretraga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzaberi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblKategorija))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzaberi)
                    .addComponent(btnOtkazi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        pretrazi();
    }//GEN-LAST:event_txtPretragaActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        pretrazi();
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void tblClanoviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClanoviMouseClicked
        if (evt.getClickCount() == 2 && tblClanovi.getSelectedRow() >= 0) {
            izaberi();
        }
    }//GEN-LAST:event_tblClanoviMouseClicked

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiActionPerformed
        izaberi();
    }//GEN-LAST:event_btnIzaberiActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        izabraniClan = null;
        dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void pretrazi() {
        ucitajClanove(txtPretraga.getText().trim());
        if (tblClanovi.getModel().getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da nadje clanove po zadatoj vrednosti!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void ucitajClanove(String parametar) {
        try {
            String p = parametar.toLowerCase();
            Clan kriterijum = new Clan(null, p, p, 0, p, "", kategorija);
            ArrayList<Clan> clanovi = ClientController.getInstance().getAllClan(kriterijum);

            ArrayList<Clan> filtrirani = new ArrayList<>();
            for (Clan c : clanovi) {
                if (c.getKategorija() != null
                        && c.getKategorija().getKategorijaID().equals(kategorija.getKategorijaID())) {
                    filtrirani.add(c);
                }
            }
            ((TableModelIzborClana) tblClanovi.getModel()).setLista(filtrirani);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita clanove: " + ex.getMessage(),
                    "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void izaberi() {
        int row = tblClanovi.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Izaberite clana iz tabele!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        izabraniClan = ((TableModelIzborClana) tblClanovi.getModel())
                .getClan(tblClanovi.convertRowIndexToModel(row));
        dispose();
    }

    public Clan getIzabraniClan() {
        return izabraniClan;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKategorija;
    private javax.swing.JTable tblClanovi;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables
}
