/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.grupa;

import controller.ClientController;
import domain.Clan;
import domain.ClanGrupe;
import domain.Grupa;
import domain.Kategorija;
import domain.Trener;
import form.clan.FormIzborClana;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import models.TableModelClanoviGrupe;


public class FormDetaljiGrupe extends javax.swing.JDialog {

    private Grupa g;
    private Clan izabraniClan;
    private javax.swing.Timer tajmerOsvezavanja;

    public FormDetaljiGrupe(JDialog parent, boolean modal, Grupa g) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Detalji grupe");
        this.g = g;
        cmbKategorija.getModel().setSelectedItem(g.getKategorija());
        cmbKategorija.setEnabled(false);
        txtNaziv.setEditable(false);
        popuniTrenere();
        txtNaziv.setText(g.getNaziv());
        txtMaxKapacitet.setText(g.getMaxKapacitet() + "");
        txtOpis.setText(g.getOpis());
        cmbTrener.getModel().setSelectedItem(g.getTrener());

        ArrayList<ClanGrupe> kopija = new ArrayList<>();
        if (g.getClanoviGrupe() != null) {
            for (ClanGrupe cg : g.getClanoviGrupe()) {
                kopija.add(new ClanGrupe(g, cg.getRb(), cg.getNapomena(), cg.getClan()));
            }
        }
        tblClanovi.setModel(new TableModelClanoviGrupe(kopija));
        tblClanovi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tblClanovi.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                ucitajIzabranuStavku();
            }
        });
        pokreniOsvezavanje();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClan = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        btnDodajClana = new javax.swing.JButton();
        btnIzmeniClana = new javax.swing.JButton();
        btnObrisiClana = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClanovi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTrener = new javax.swing.JComboBox();
        cmbKategorija = new javax.swing.JComboBox();
        txtNaziv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        btnZatvori = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMaxKapacitet = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupa"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clanovi grupe"));

        jLabel5.setText("Clan:");

        jLabel6.setText("Napomena:");

        txtClan.setEditable(false);
        txtClan.setToolTipText("Kliknite na lupu da izaberete clana");

        btnPretraga.setText("🔍");
        btnPretraga.setToolTipText("Pretraga clanova kategorije");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane2.setViewportView(txtNapomena);

        btnDodajClana.setBackground(new java.awt.Color(153, 204, 255));
        btnDodajClana.setText("Dodaj clana");
        btnDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajClanaActionPerformed(evt);
            }
        });

        btnIzmeniClana.setBackground(new java.awt.Color(153, 204, 255));
        btnIzmeniClana.setText("Izmeni clana");
        btnIzmeniClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniClanaActionPerformed(evt);
            }
        });

        btnObrisiClana.setBackground(new java.awt.Color(153, 204, 255));
        btnObrisiClana.setText("Obrisi clana");
        btnObrisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiClanaActionPerformed(evt);
            }
        });

        tblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblClanovi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDodajClana, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniClana, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiClana, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtClan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajClana)
                    .addComponent(btnIzmeniClana)
                    .addComponent(btnObrisiClana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Trener:");

        jLabel2.setText("Kategorija:");

        jLabel3.setText("Naziv:");

        jLabel4.setText("Opis:");

        cmbTrener.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbKategorija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKategorija.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKategorijaItemStateChanged(evt);
            }
        });

        txtNaziv.setText("Pavle Savic");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        txtOpis.setText("Crveni.");
        jScrollPane1.setViewportView(txtOpis);

        btnZatvori.setBackground(new java.awt.Color(153, 204, 255));
        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        btnObrisi.setBackground(new java.awt.Color(153, 204, 255));
        btnObrisi.setText("Obrisi grupu");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzmeni.setBackground(new java.awt.Color(153, 204, 255));
        btnIzmeni.setText("Izmeni grupu");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel7.setText("Maksimalni kapacitet:");

        txtMaxKapacitet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbKategorija, 0, 318, Short.MAX_VALUE)
                            .addComponent(cmbTrener, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNaziv)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaxKapacitet))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIzmeni, btnObrisi, btnZatvori});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaxKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZatvori)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "obrisete ovu grupu?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                ClientController.getInstance().deleteGrupa(g);
                FormPretragaGrupe fp = (FormPretragaGrupe) getParent();
                fp.refreshTable();
                JOptionPane.showMessageDialog(this, "Sistem je obrisao grupu");
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Sistem ne moze da obrise grupu", JOptionPane.ERROR_MESSAGE);
               // Logger.getLogger(FormDetaljiGrupe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        try {

            Trener trener = (Trener) cmbTrener.getSelectedItem();
            String opis = txtOpis.getText();
            int maxKapacitet = Integer.parseInt(txtMaxKapacitet.getText());

            TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();

            g.setTrener(trener);
            g.setOpis(opis);
            g.setBrojClanova(tm.getLista().size());
            g.setMaxKapacitet(maxKapacitet);
            g.setClanoviGrupe(tm.getLista());

            setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
            String izvestajMail;
            try {
                izvestajMail = ClientController.getInstance().updateGrupa(g);
            } finally {
                setCursor(java.awt.Cursor.getDefaultCursor());
            }
            FormPretragaGrupe fp = (FormPretragaGrupe) getParent();
            fp.refreshTable();
            JOptionPane.showMessageDialog(this, "Sistem je izmenio grupu\n\n" + izvestajMail);
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Sistem ne moze da izmeni grupu", JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(FormDetaljiGrupe.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        FormIzborClana forma = new FormIzborClana(this, true, g.getKategorija());
        forma.setVisible(true);

        Clan clan = forma.getIzabraniClan();
        if (clan != null) {
            izabraniClan = clan;
            txtClan.setText(clan.getIme() + " " + clan.getPrezime()
                    + " (" + clan.getEmail() + ")");
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajClanaActionPerformed

        if (izabraniClan == null) {
            JOptionPane.showMessageDialog(this, "Izaberite clana klikom na lupu!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();

        if (tm.postojiClan(izabraniClan)) {
            JOptionPane.showMessageDialog(this, "Vec ste uneli ovog clana!");
            return;
        }

        ClanGrupe cg = new ClanGrupe(g, -1, procitajNapomenu(), izabraniClan);
        tm.dodajClana(cg);
        ocistiPoljaClana();

    }//GEN-LAST:event_btnDodajClanaActionPerformed

    private void btnIzmeniClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniClanaActionPerformed

        int row = tblClanovi.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Oznacite u tabeli clana kojeg menjate!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        FormIzborClana forma = new FormIzborClana(this, true, g.getKategorija());
        forma.setVisible(true);
        Clan noviClan = forma.getIzabraniClan();

        if (noviClan == null) {
            return;
        }

        TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();

        if (tm.postojiClanOsimReda(noviClan, row)) {
            JOptionPane.showMessageDialog(this, "Ovaj clan je vec u grupi!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        tm.izmeniClana(row, noviClan, procitajNapomenu());
        ocistiPoljaClana();
        JOptionPane.showMessageDialog(this, "Clan u stavci " + (row + 1) + " je izmenjen.");

    }//GEN-LAST:event_btnIzmeniClanaActionPerformed

    private void btnObrisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiClanaActionPerformed

        int row = tblClanovi.getSelectedRow();

        if (row >= 0) {
            TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();
            tm.obrisiClana(row);
            ocistiPoljaClana();
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite stavku u tabeli koju brisete!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnObrisiClanaActionPerformed

    private void cmbKategorijaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKategorijaItemStateChanged
    }//GEN-LAST:event_cmbKategorijaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajClana;
    private javax.swing.JButton btnIzmeniClana;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiClana;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JComboBox cmbKategorija;
    private javax.swing.JComboBox cmbTrener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblClanovi;
    private javax.swing.JTextField txtClan;
    private javax.swing.JFormattedTextField txtMaxKapacitet;
    private javax.swing.JTextArea txtNapomena;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    // End of variables declaration//GEN-END:variables

    public void popuniTrenere() {
        try {
            ArrayList<Trener> treneri = ClientController.getInstance()
                    .getAllTrener(new Trener(null, "", "", "", 0));

            cmbTrener.removeAllItems();

            for (Trener trener : treneri) {
                cmbTrener.addItem(trener);
            }

        } catch (Exception ex) {
            Logger.getLogger(FormDetaljiGrupe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void osveziClanoveGrupe() {
        if (!(tblClanovi.getModel() instanceof TableModelClanoviGrupe)) {
            return;
        }
        TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();
        if (tm.getRowCount() == 0) {
            return;
        }
        try {
            ArrayList<String> uklonjeni = tm.osveziSaServera(g.getKategorija().getKategorijaID());
            osveziIzabranogClana(tm);
            if (!uklonjeni.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sledeci clanovi su uklonjeni iz grupe jer su obrisani "
                        + "ili vise ne pripadaju kategoriji grupe:\n" + String.join(", ", uklonjeni),
                        "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormDetaljiGrupe.class.getName()).log(Level.WARNING, "Osvezavanje clanova grupe nije uspelo", ex);
        }
    }

    private void osveziIzabranogClana(TableModelClanoviGrupe tm) {
        if (izabraniClan == null) {
            return;
        }
        for (ClanGrupe cg : tm.getLista()) {
            if (cg.getClan().getClanID().equals(izabraniClan.getClanID())) {
                izabraniClan = cg.getClan();
                txtClan.setText(izabraniClan.getIme() + " " + izabraniClan.getPrezime()
                        + " (" + izabraniClan.getEmail() + ")");
                return;
            }
        }
    }

    private void pokreniOsvezavanje() {
        tajmerOsvezavanja = new javax.swing.Timer(5000, e -> osveziClanoveGrupe());
        tajmerOsvezavanja.start();
    }

    @Override
    public void dispose() {
        if (tajmerOsvezavanja != null) {
            tajmerOsvezavanja.stop();
        }
        super.dispose();
    }

    private void ucitajIzabranuStavku() {
        int row = tblClanovi.getSelectedRow();
        if (row < 0 || !(tblClanovi.getModel() instanceof TableModelClanoviGrupe)) {
            return;
        }
        ClanGrupe cg = ((TableModelClanoviGrupe) tblClanovi.getModel()).getStavka(row);
        izabraniClan = cg.getClan();
        txtClan.setText(izabraniClan.getIme() + " " + izabraniClan.getPrezime()
                + " (" + izabraniClan.getEmail() + ")");
        txtNapomena.setText("/".equals(cg.getNapomena()) ? "" : cg.getNapomena());
    }

    private String procitajNapomenu() {
        String napomena = txtNapomena.getText().trim();
        return napomena.isEmpty() ? "/" : napomena;
    }

    private void ocistiPoljaClana() {
        izabraniClan = null;
        txtClan.setText("");
        txtNapomena.setText("");
        tblClanovi.clearSelection();
    }

}
