/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import controller.ClientController;
import domain.Administrator;
import domain.Clan;
import domain.ClanGrupe;
import domain.Grupa;
import domain.Kategorija;
import domain.Trener;
import form.clan.FormIzborClana;
import form.clan.FormNoviClan;
import form.clan.FormPretragaClana;
import form.grupa.FormPretragaGrupe;
import form.trener.FormNoviTrener;
import form.trener.FormPretragaTrenera;
import java.awt.event.ItemEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.TableModelClanoviGrupe;
import session.Session;


public class MainForm extends javax.swing.JFrame {

    private Administrator ulogovani;
    private Clan izabraniClan;
    private boolean ucitavanjeKategorija;
    private javax.swing.Timer tajmerOsvezavanja;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        Session.getInstance().setMf(this);
        lblUlogovani.setText("Ulogovani administrator: " + ulogovani);
        setTitle("Klijentska forma");

        popuniTrenere();
        popuniKategorije();
        tblClanovi.setModel(new TableModelClanoviGrupe());
        tblClanovi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tblClanovi.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                ucitajIzabranuStavku();
            }
        });
        pokreniOsvezavanje();

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int response = JOptionPane.showConfirmDialog(
                        null,
                        "Da li ste sigurni da zelite da se odjavite?",
                        "Confirm Exit",
                        JOptionPane.YES_NO_OPTION
                );

                if (response == JOptionPane.YES_OPTION) {
                    try {
                        ClientController.getInstance().logout(ulogovani);
                        zatvoriProgram();
                    } catch (Exception ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        btnDodajClana = new javax.swing.JButton();
        btnIzmeniClana = new javax.swing.JButton();
        btnObrisiClana = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClanovi = new javax.swing.JTable();
        btnPretraga = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTrener = new javax.swing.JComboBox();
        cmbKategorija = new javax.swing.JComboBox();
        txtNaziv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtMaxKapacitet = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNoviClan = new javax.swing.JMenuItem();
        miPretragaClana = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miNoviTrener = new javax.swing.JMenuItem();
        miPretragaTrenera = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miPretragaGrupe = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupa"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clanovi grupe"));

        jLabel5.setText("Clan:");

        jLabel6.setText("Napomena:");

        txtClan.setEditable(false);
        txtClan.setToolTipText("Kliknite na lupu da izaberete clana");

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane2.setViewportView(txtNapomena);

        btnDodajClana.setBackground(new java.awt.Color(153, 204, 255));
        btnDodajClana.setText("Dodaj clana");
        btnDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajClanaActionPerformed(evt);
            }
        });

        btnIzmeniClana.setBackground(new java.awt.Color(153, 204, 255));
        btnIzmeniClana.setText("Zameni clana");
        btnIzmeniClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniClanaActionPerformed(evt);
            }
        });

        btnObrisiClana.setBackground(new java.awt.Color(153, 204, 255));
        btnObrisiClana.setText("Obrisi clana");
        btnObrisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiClanaActionPerformed(evt);
            }
        });

        tblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblClanovi);

        btnPretraga.setText("🔍");
        btnPretraga.setToolTipText("Pretraga clanova kategorije");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDodajClana, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniClana, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiClana, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtClan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajClana)
                    .addComponent(btnIzmeniClana)
                    .addComponent(btnObrisiClana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSacuvaj.setBackground(new java.awt.Color(153, 204, 255));
        btnSacuvaj.setText("Sacuvaj grupu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel1.setText("Trener:");

        jLabel2.setText("Kategorija:");

        jLabel3.setText("Naziv:");

        jLabel4.setText("Opis:");

        cmbTrener.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbKategorija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKategorija.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKategorijaItemStateChanged(evt);
            }
        });
        cmbKategorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKategorijaActionPerformed(evt);
            }
        });

        txtNaziv.setText("Pavle Savic");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        txtOpis.setText("Crveni.");
        jScrollPane1.setViewportView(txtOpis);

        jLabel7.setText("Maksimalni kapacitet:");

        txtMaxKapacitet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTrener, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNaziv)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaxKapacitet)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaxKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu6.setText("Clan");

        miNoviClan.setText("Novi clan");
        miNoviClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviClanActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviClan);

        miPretragaClana.setText("Pretraga clana");
        miPretragaClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaClanaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaClana);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Trener");

        miNoviTrener.setText("Novi trener");
        miNoviTrener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviTrenerActionPerformed(evt);
            }
        });
        jMenu8.add(miNoviTrener);

        miPretragaTrenera.setText("Pretraga trenera");
        miPretragaTrenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaTreneraActionPerformed(evt);
            }
        });
        jMenu8.add(miPretragaTrenera);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Grupa");

        miPretragaGrupe.setText("Pretraga grupe");
        miPretragaGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaGrupeActionPerformed(evt);
            }
        });
        jMenu9.add(miPretragaGrupe);

        jMenuBar1.add(jMenu9);

        jMenu7.setText("Odjava");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu7.add(miOdjava);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUlogovani)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviClanActionPerformed
        new FormNoviClan(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviClanActionPerformed

    private void miPretragaClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaClanaActionPerformed
        new FormPretragaClana(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaClanaActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                ClientController.getInstance().logout(ulogovani);
                new LoginForma().setVisible(true);
                Session.getInstance().setUlogovani(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miNoviTrenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviTrenerActionPerformed
        new FormNoviTrener(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviTrenerActionPerformed

    private void miPretragaTreneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaTreneraActionPerformed
        new FormPretragaTrenera(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaTreneraActionPerformed

    private void miPretragaGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaGrupeActionPerformed
        new FormPretragaGrupe(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaGrupeActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        if (!(cmbKategorija.getSelectedItem() instanceof Kategorija)) {
            JOptionPane.showMessageDialog(this, "Prvo izaberite kategoriju grupe!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Kategorija kategorija = (Kategorija) cmbKategorija.getSelectedItem();

        FormIzborClana forma = new FormIzborClana(this, true, kategorija);
        forma.setVisible(true);

        Clan clan = forma.getIzabraniClan();
        if (clan != null) {
            izabraniClan = clan;
            txtClan.setText(clan.getIme() + " " + clan.getPrezime()
                    + " (" + clan.getEmail() + ")");
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajClanaActionPerformed

        if (izabraniClan == null) {
            JOptionPane.showMessageDialog(this, "Izaberite clana klikom na lupu!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();

        if (tm.postojiClan(izabraniClan)) {
            JOptionPane.showMessageDialog(this, "Vec ste uneli ovog clana!");
            return;
        }

        ClanGrupe cg = new ClanGrupe(null, -1, procitajNapomenu(), izabraniClan);
        tm.dodajClana(cg);
        ocistiPoljaClana();

    }//GEN-LAST:event_btnDodajClanaActionPerformed

    private void btnIzmeniClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniClanaActionPerformed

        int row = tblClanovi.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Oznacite u tabeli clana kojeg menjate!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!(cmbKategorija.getSelectedItem() instanceof Kategorija)) {
            JOptionPane.showMessageDialog(this, "Prvo izaberite kategoriju grupe!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        FormIzborClana forma = new FormIzborClana(this, true, (Kategorija) cmbKategorija.getSelectedItem());
        forma.setVisible(true);
        Clan noviClan = forma.getIzabraniClan();

        if (noviClan == null) {
            return;
        }

        TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();

        if (tm.postojiClanOsimReda(noviClan, row)) {
            JOptionPane.showMessageDialog(this, "Ovaj clan je vec u grupi!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        tm.izmeniClana(row, noviClan, procitajNapomenu());
        ocistiPoljaClana();
        JOptionPane.showMessageDialog(this, "Clan u stavci " + (row + 1) + " je izmenjen.");

    }//GEN-LAST:event_btnIzmeniClanaActionPerformed

    private void btnObrisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiClanaActionPerformed

        int row = tblClanovi.getSelectedRow();

        if (row >= 0) {
            TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();
            tm.obrisiClana(row);
            ocistiPoljaClana();
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite stavku u tabeli koju brisete!",
                    "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnObrisiClanaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        if (txtMaxKapacitet.getText().isEmpty() || txtNaziv.getText().isEmpty()
                || txtOpis.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
            return;
        }

        try {
            Trener trener = (Trener) cmbTrener.getSelectedItem();
            Kategorija kategorija = (Kategorija) cmbKategorija.getSelectedItem();
            String naziv = txtNaziv.getText();
            String opis = txtOpis.getText();
            int maxKapacitet = Integer.parseInt(txtMaxKapacitet.getText());

            TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();

            Grupa g = new Grupa(null, naziv, opis, tm.getLista().size(),
                    maxKapacitet, kategorija, trener, ulogovani, tm.getLista());

            setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
            String izvestajMail;
            try {
                izvestajMail = ClientController.getInstance().addGrupa(g);
            } finally {
                setCursor(java.awt.Cursor.getDefaultCursor());
            }
            txtNaziv.setText("");
            txtOpis.setText("");
            txtNapomena.setText("");
            txtMaxKapacitet.setText("");
            tm.ocisti();
            ocistiPoljaClana();
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana grupa!\n\n" + izvestajMail);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira grupu", 
                    "Greska", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, ex.getMessage());
            //            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void cmbKategorijaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKategorijaItemStateChanged

        if (ucitavanjeKategorija || evt.getStateChange() != ItemEvent.SELECTED) {
            return;
        }
        if (cmbKategorija.getSelectedItem() instanceof Kategorija) {
            ((TableModelClanoviGrupe) tblClanovi.getModel()).ocisti();
            ocistiPoljaClana();
        }

    }//GEN-LAST:event_cmbKategorijaItemStateChanged

    private void cmbKategorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategorijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKategorijaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajClana;
    private javax.swing.JButton btnIzmeniClana;
    private javax.swing.JButton btnObrisiClana;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbKategorija;
    private javax.swing.JComboBox cmbTrener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNoviClan;
    private javax.swing.JMenuItem miNoviTrener;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaClana;
    private javax.swing.JMenuItem miPretragaGrupe;
    private javax.swing.JMenuItem miPretragaTrenera;
    private javax.swing.JTable tblClanovi;
    private javax.swing.JTextField txtClan;
    private javax.swing.JFormattedTextField txtMaxKapacitet;
    private javax.swing.JTextArea txtNapomena;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    // End of variables declaration//GEN-END:variables

    public void popuniTrenere() {
        try {
            ArrayList<Trener> treneri = ClientController.getInstance()
                    .getAllTrener(new Trener(null, "", "", "", 0));

            cmbTrener.removeAllItems();

            for (Trener trener : treneri) {
                cmbTrener.addItem(trener);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniKategorije() {
        Object prethodna = cmbKategorija.getSelectedItem();
        ucitavanjeKategorija = true;
        boolean zadrzana = false;
        try {
            ArrayList<Kategorija> kategorije = ClientController.getInstance()
                    .getAllKategorija(new Kategorija(null, "", ""));

            cmbKategorija.removeAllItems();

            for (Kategorija kategorija : kategorije) {
                cmbKategorija.addItem(kategorija);
                if (prethodna instanceof Kategorija && kategorija.getKategorijaID()
                        .equals(((Kategorija) prethodna).getKategorijaID())) {
                    cmbKategorija.setSelectedItem(kategorija);
                    zadrzana = true;
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            ucitavanjeKategorija = false;
        }

        if (!zadrzana && tblClanovi.getModel() instanceof TableModelClanoviGrupe) {
            ((TableModelClanoviGrupe) tblClanovi.getModel()).ocisti();
            ocistiPoljaClana();
        }
    }

    public void osveziClanoveGrupe() {
        if (!(tblClanovi.getModel() instanceof TableModelClanoviGrupe)) {
            return;
        }
        TableModelClanoviGrupe tm = (TableModelClanoviGrupe) tblClanovi.getModel();
        if (tm.getRowCount() == 0) {
            return;
        }
        try {
            ArrayList<String> uklonjeni = tm.osveziSaServera(cmbKategorija.getSelectedItem() instanceof Kategorija
                    ? ((Kategorija) cmbKategorija.getSelectedItem()).getKategorijaID() : null);
            osveziIzabranogClana(tm);
            if (!uklonjeni.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sledeci clanovi su uklonjeni iz grupe jer su obrisani "
                        + "ili vise ne pripadaju kategoriji grupe:\n" + String.join(", ", uklonjeni),
                        "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.WARNING, "Osvezavanje clanova grupe nije uspelo", ex);
        }
    }

    private void osveziIzabranogClana(TableModelClanoviGrupe tm) {
        if (izabraniClan == null) {
            return;
        }
        for (ClanGrupe cg : tm.getLista()) {
            if (cg.getClan().getClanID().equals(izabraniClan.getClanID())) {
                izabraniClan = cg.getClan();
                txtClan.setText(izabraniClan.getIme() + " " + izabraniClan.getPrezime()
                        + " (" + izabraniClan.getEmail() + ")");
                return;
            }
        }
    }

    protected void zatvoriProgram() {
        System.exit(0);
    }

    private void pokreniOsvezavanje() {
        tajmerOsvezavanja = new javax.swing.Timer(5000, e -> osveziClanoveGrupe());
        tajmerOsvezavanja.start();
    }

    @Override
    public void dispose() {
        if (tajmerOsvezavanja != null) {
            tajmerOsvezavanja.stop();
        }
        super.dispose();
    }

    private void ucitajIzabranuStavku() {
        int row = tblClanovi.getSelectedRow();
        if (row < 0 || !(tblClanovi.getModel() instanceof TableModelClanoviGrupe)) {
            return;
        }
        ClanGrupe cg = ((TableModelClanoviGrupe) tblClanovi.getModel()).getStavka(row);
        izabraniClan = cg.getClan();
        txtClan.setText(izabraniClan.getIme() + " " + izabraniClan.getPrezime()
                + " (" + izabraniClan.getEmail() + ")");
        txtNapomena.setText("/".equals(cg.getNapomena()) ? "" : cg.getNapomena());
    }

    private String procitajNapomenu() {
        String napomena = txtNapomena.getText().trim();
        return napomena.isEmpty() ? "/" : napomena;
    }

    private void ocistiPoljaClana() {
        izabraniClan = null;
        txtClan.setText("");
        txtNapomena.setText("");
        tblClanovi.clearSelection();
    }

}
